# Generated by Django 6.0.5 on 2026-05-23 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='state',
            field=models.CharField(blank=True, help_text='State assignment for officers/admins', max_length=100, null=True),
        ),
    ]
