# Generated by Django 6.0.5 on 2026-05-23 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, help_text='City assignment for officers/admins', max_length=100, null=True),
        ),
    ]
