from django.contrib import admin
from django.utils.html import format_html
from .models import (
    Report, ReportMedia, OfficerAssignment, ResolutionUpdate, 
    InfrastructureQRCode, CommunityVerification, AccessibilityCertification, 
    InfrastructureReview, AccessibilityIndex, RouteAccessibility, GeofenceAlertSubscription
)

class ReportMediaInline(admin.TabularInline):
    model = ReportMedia
    extra = 1
    readonly_fields = ('media_preview',)

    def media_preview(self, obj):
        if obj.file:
            return format_html('<img src="{}" style="max-height: 100px;"/>', obj.file.url)
        return "No media"

@admin.register(Report)
class ReportAdmin(admin.ModelAdmin):
    list_display = ('id', 'colored_status', 'title', 'city', 'severity', 'priority_score', 'sla_warning', 'reporter', 'created_at')
    list_filter = ('status', 'severity', 'category', 'city', 'state')
    search_fields = ('title', 'description', 'reporter__username', 'city')
    inlines = [ReportMediaInline]
    actions = ['verify_reports', 'resolve_reports', 'recalculate_priority']
    
    fieldsets = (
        ('General Information', {
            'fields': ('title', 'description', 'category', 'severity', 'status')
        }),
        ('Location Details', {
            'fields': ('address', 'city', 'state', ('latitude', 'longitude')),
            'classes': ('collapse',)
        }),
        ('Professional Analytics (AI)', {
            'fields': ('priority_score', 'ai_summary', 'qr_code'),
            'description': 'Data generated by Gemini AI and Geofence Analysis'
        }),
        ('Meta Data', {
            'fields': ('reporter', 'is_anonymous', 'escalation_level', 'next_escalation_at', 'sla_deadline', 'is_escalated'),
            'classes': ('collapse',)
        }),
    )
    readonly_fields = ('priority_score', 'ai_summary', 'qr_code')

    def colored_status(self, obj):
        colors = {
            'pending': 'orange',
            'verified': 'blue',
            'in_progress': 'purple',
            'resolved': 'green',
            'rejected': 'red'
        }
        return format_html(
            '<span style="color: {}; font-weight: bold;">{}</span>',
            colors.get(obj.status, 'black'),
            obj.get_status_display()
        )
    colored_status.short_description = 'Status'

    def sla_warning(self, obj):
        from django.utils import timezone
        if obj.status != 'resolved' and obj.sla_deadline and obj.sla_deadline < timezone.now():
            return format_html('<span style="color: red; font-weight: bold;">🔴 OVERDUE</span>')
        return obj.sla_deadline.strftime('%d %b') if obj.sla_deadline else "No SLA"
    sla_warning.short_description = 'SLA Deadline'

    def get_queryset(self, request):
        qs = super().get_queryset(request)
        if request.user.is_superuser or request.user.role == 'superadmin':
            return qs
        if request.user.role in ['admin', 'officer']:
            if request.user.city:
                return qs.filter(city__iexact=request.user.city)
            elif request.user.state:
                return qs.filter(state__iexact=request.user.state)
        return qs

    def verify_reports(self, request, queryset):
        queryset.update(status='verified')
        self.message_user(request, "Selected reports have been verified.")
    verify_reports.short_description = "Mark reports as Verified Barrier"

    def resolve_reports(self, request, queryset):
        queryset.update(status='resolved')
        self.message_user(request, "Selected reports have been resolved.")
    resolve_reports.short_description = "Mark reports as Resolved"

    def recalculate_priority(self, request, queryset):
        for rep in queryset:
            rep.save() 
        self.message_user(request, "Priority scores recalculated successfully.")
    recalculate_priority.short_description = "Recalculate Priority Scores"

@admin.register(InfrastructureQRCode)
class InfrastructureQRCodeAdmin(admin.ModelAdmin):
    list_display = ('location_name', 'entity_type', 'health_score', 'qr_preview')
    list_filter = ('entity_type',)
    actions = ['generate_qrs']
    
    def generate_qrs(self, request, queryset):
        from .services import QRCodeService
        for infra in queryset:
            QRCodeService.generate_for_infrastructure(infra)
        self.message_user(request, "QR Codes generated specifically for public auditing.")
    generate_qrs.short_description = "Generate Official Public Audit QRs"
    
    def qr_preview(self, obj):
        if obj.qr_code_image:
            return format_html('<img src="{}" style="max-height: 50px;"/>', obj.qr_code_image.url)
        return "N/A"

@admin.register(AccessibilityCertification)
class AccessibilityCertificationAdmin(admin.ModelAdmin):
    list_display = ('infrastructure', 'compliance_score', 'issued_date', 'expiry_date')
    list_filter = ('compliance_score',)

@admin.register(AccessibilityIndex)
class AccessibilityIndexAdmin(admin.ModelAdmin):
    list_display = ('region_name', 'region_type', 'overall_index', 'last_updated')
    list_filter = ('region_type',)

@admin.register(CommunityVerification)
class CommunityVerificationAdmin(admin.ModelAdmin):
    list_display = ('report', 'verifier', 'is_valid', 'timestamp')

@admin.register(InfrastructureReview)
class InfrastructureReviewAdmin(admin.ModelAdmin):
    list_display = ('infrastructure', 'user', 'wheelchair_rating', 'timestamp')

@admin.register(RouteAccessibility)
class RouteAccessibilityAdmin(admin.ModelAdmin):
    list_display = ('user', 'start_location', 'end_location', 'is_fully_accessible', 'obstacles_count')

@admin.register(GeofenceAlertSubscription)
class GeofenceAlertSubscriptionAdmin(admin.ModelAdmin):
    list_display = ('user', 'latitude', 'longitude', 'radius_meters', 'is_active')

@admin.register(ResolutionUpdate)
class ResolutionUpdateAdmin(admin.ModelAdmin):
    list_display = ('report', 'officer', 'colored_rating', 'is_verified_by_citizen', 'resolved_at')
    list_filter = ('is_verified_by_citizen', 'citizen_rating')
    readonly_fields = ('citizen_rating', 'citizen_feedback', 'is_verified_by_citizen')

    def colored_rating(self, obj):
        if not obj.citizen_rating: return "Unrated"
        color = "green" if obj.citizen_rating >= 4 else "orange" if obj.citizen_rating >= 3 else "red"
        return format_html('<span style="color: {}; font-weight: bold;">{} ★</span>', color, obj.citizen_rating)
    colored_rating.short_description = 'Citizen Rating'

admin.site.register(ReportMedia)
admin.site.register(OfficerAssignment)

# Styling the Admin header
admin.site.site_header = "Accessible India - Admin Governance Portal"
admin.site.site_title = "Admin Portal"
admin.site.index_title = "Governance Dashboard"
