# Generated by Django 6.0.5 on 2026-05-20 03:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessibilityIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_type', models.CharField(choices=[('state', 'State'), ('city', 'City'), ('district', 'District')], max_length=50)),
                ('region_name', models.CharField(max_length=255)),
                ('infrastructure_score', models.FloatField(default=0.0)),
                ('resolution_speed_score', models.FloatField(default=0.0)),
                ('citizen_satisfaction_score', models.FloatField(default=0.0)),
                ('overall_index', models.FloatField(default=0.0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='InfrastructureQRCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=255)),
                ('entity_type', models.CharField(choices=[('station', 'Railway/Metro Station'), ('mall', 'Shopping Mall'), ('hospital', 'Hospital'), ('government', 'Government Building'), ('college', 'College/University')], max_length=100)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('qr_code_image', models.ImageField(blank=True, null=True, upload_to='infrastructure_qr/')),
                ('health_score', models.IntegerField(default=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='report',
            name='escalation_level',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='report',
            name='next_escalation_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='CommunityVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_valid', models.BooleanField(default=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='reports.report')),
                ('verifier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AccessibilityCertification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compliance_score', models.IntegerField(default=0)),
                ('certificate_pdf', models.FileField(blank=True, null=True, upload_to='certifications/')),
                ('issued_date', models.DateTimeField(auto_now_add=True)),
                ('expiry_date', models.DateTimeField(blank=True, null=True)),
                ('auditor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('infrastructure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='reports.infrastructureqrcode')),
            ],
        ),
        migrations.CreateModel(
            name='InfrastructureReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wheelchair_rating', models.IntegerField(default=5)),
                ('tactile_rating', models.IntegerField(default=5)),
                ('elevator_rating', models.IntegerField(default=5)),
                ('restroom_rating', models.IntegerField(default=5)),
                ('review_text', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('infrastructure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='reports.infrastructureqrcode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
