# Generated by Django 6.0.5 on 2026-05-23 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_accessibilityindex_infrastructureqrcode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='state',
            field=models.CharField(blank=True, help_text='State where the issue was reported', max_length=100, null=True),
        ),
    ]
