# Generated by Django 6.0.5 on 2026-05-23 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_report_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='city',
            field=models.CharField(blank=True, help_text='City where the issue was reported', max_length=100, null=True),
        ),
    ]
