# Generated by Django 6.0.5 on 2026-06-20 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_geofencealertsubscription_routeaccessibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='is_escalated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='report',
            name='sla_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resolutionupdate',
            name='citizen_feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resolutionupdate',
            name='citizen_rating',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True),
        ),
        migrations.AddField(
            model_name='resolutionupdate',
            name='is_verified_by_citizen',
            field=models.BooleanField(default=False),
        ),
    ]
